### ISSUE TITLE
npm-asset/socket.io issue

### ISSUE THREAD

**Issue by santehnick** [francoispluchino/composer-asset-plugin#88]
composer require npm-asset/socket.io:1.2.1

[ErrorException]
Undefined index: repository

I deleted a vendor directory, but this not decided my problem.

https://www.npmjs.com/package/socket.io

**Comment by francoispluchino** [comment]
I suppose that you don't use the last version (beta 4 or dev) of this plugin.

**Comment by francoispluchino** [comment]
With the last version, you will have an exception because this dependency required 2 version of the same package (debug [1.0.2, 0.7.4]. Composer is not able to handle this case.

For NPM, only the simple dependencies can be managed with this plugin, on the other hand, for Bower, all dependencies can be managed.
