### ISSUE TITLE
Releases without the "v" prefix not recognized

### ISSUE THREAD

**Issue by mbman** [francoispluchino/composer-asset-plugin#97]
https://github.com/vitalets/angular-xeditable/releases shows the latest release being "0.1.8" (note the lack of "v" prefix) and I set the dependecy to: `"bower-asset/angular-xeditable": "0.1.8"` it fails with "not found in any version" error. If  `"bower-asset/angular-xeditable": "*"` is used in composer.json it finds a proper version, but often gets into memory limit problems on update.

Why isn't it recognizing releases?

**Comment by francoispluchino** [comment]
Do you use the latest stable version?

Because, I just do the test, and it's good for me:

```
$ composer install --prefer-dist
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing bower-asset/angular (v1.3.13)
    Downloading: 100%
    Extracting archive

  - Installing bower-asset/angular-xeditable (0.1.8)
    Downloading: 100%
    Extracting archive

Writing lock file
Generating autoload files
```

I guess this is not the case, because you import all versions of AngularJs, whereas with the stable version, the plugin does not import `build` versions.

To prevent the importation of all versions, read the doc [How to reduce the number of requests for getting the package definitions?](https://github.com/francoispluchino/composer-asset-plugin/blob/1.0/Resources/doc/faqs.md#how-to-reduce-the-number-of-requests-for-getting-the-package-definitions).

**Comment by mbman** [comment]
Using the latest stable version, works well with `--prefer-dist`. Thanks
